### ISSUE TITLE
Modeline color when buffer is modified

### ISSUE THREAD

**Issue by traxyax** [manateelazycat/awesome-tray#107]
I would like to change the `mode-line-active-color` dynamically if a buffer is modified. Actually the only way is to reactivate the mode. I would like to know if there is another way.

**Comment by manateelazycat** [comment]
I use my https://github.com/manateelazycat/auto-save, I don't need modified status.

Anyway, PR are welcome. ;)

**Comment by traxyax** [comment]
I've submitted a PR.
