### ISSUE TITLE
与tabbar有冲突，enable awesome-tray之后，tabbar的标签变的很小

### ISSUE THREAD

**Issue by speeeeed** [manateelazycat/awesome-tray#11]
与tabbar有冲突，enable awesome-tray之后，tabbar的标签变的很小。

**Comment by speeeeed** [comment]
https://github.com/manateelazycat/awesome-tray/issues/6
如上issue已解决我的问题。

**Comment by manateelazycat** [comment]
使用awesome-tab.el吧，tabber已经落后了
