### ISSUE TITLE
java-ts-mode 中 belong信息没有显示

### ISSUE THREAD

**Issue by Peter-Chou** [manateelazycat/awesome-tray#112]
我在python-ts-mode 中 belong信息可以正常显示：

![image](https://github.com/manateelazycat/awesome-tray/assets/28672146/ce330520-5ec2-452a-abcd-c77a4c5e990c)

但是在java-ts-mode中belong信息就没有了：

![image](https://github.com/manateelazycat/awesome-tray/assets/28672146/b8740dee-56a9-4cfd-96c2-180da557cd0b)
上面显示是鼠标悬停在springboot 的controller类的方法中，按理belong应该返回内容的呀

大佬有空能看下吗，是不是有什么bug ？

**Comment by manateelazycat** [comment]
能给一下源代吗？ 我这边没法测试

**Comment by Peter-Chou** [comment]
代码的话，可以使用https://github.com/BuntyRaghani/spring-boot-hello-world 这个demo的就行，麻烦大佬看一下，谢谢啦

**Comment by manateelazycat** [comment]
![截图 2023-09-16 10-38-25](https://github.com/manateelazycat/awesome-tray/assets/237487/2f0cee1f-7f0b-4fd6-a443-99dc7a91ffb2)

最新版已经修复了， 感谢反馈
