### ISSUE TITLE
belong support issue on cpp function define

### ISSUE THREAD

**Issue by Peter-Chou** [manateelazycat/awesome-tray#114]
太谢谢大佬啦，这个项目里的显示我这里也是正常的  

![image](https://github.com/manateelazycat/awesome-tray/assets/28672146/e33fa1c6-c800-4530-bc99-14efe4993497)

但是在复杂点的项目里还是显示不出，我比较了下应该是比demo项目中增加了namespace和class，如图

在header文件中
![image](https://github.com/manateelazycat/awesome-tray/assets/28672146/d0aeec83-2bd4-489a-8883-45d82d9ecc53)
  
在cpp文件中
![image](https://github.com/manateelazycat/awesome-tray/assets/28672146/20887332-3efd-49a1-9c05-f2b051ae1e51)

图片中代码地址：https://github.com/Peter-Chou/transformer_cpp_tokenizers

大佬有时间的话，麻烦抽空看下，非常感谢啦

_Originally posted by @Peter-Chou in https://github.com/manateelazycat/awesome-tray/issues/113#issuecomment-1774658336_

**Comment by manateelazycat** [comment]
belong模块是用于探测函数的， 不是用于面包屑场景的。

**Comment by Peter-Chou** [comment]
额，好吧，虽然仔细看的话，其实是class的method没显示出来=，=，whatever.
