### ISSUE TITLE
belong support issue on cpp method define [final attempt]

### ISSUE THREAD

**Issue by Peter-Chou** [manateelazycat/awesome-tray#115]
嗯~~~好吧。上图header文件有点歧义 ，我更新下 ：  
  
![image](https://github.com/manateelazycat/awesome-tray/assets/28672146/3aa420c6-8de2-416a-aced-4e6069da079b)

仔细看图的话会发现：header文件中和cpp文件中其实 **class的method** belong并没有显示出来。  
和面包屑比较并非希望belong变成面包屑，只是想突出下问题。   
I hope we are on the same page...
  
_Originally posted by @Peter-Chou in https://github.com/manateelazycat/awesome-tray/issues/114#issuecomment-1775202064_

**Comment by manateelazycat** [comment]
给源文件吧， 我不承诺一定修复， 时间有限。

**Comment by Peter-Chou** [comment]
仓库地址：https://github.com/Peter-Chou/transformer_cpp_tokenizers，麻烦大佬有空看下啦，结果如何不重要。佛家有云：无心而为。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/awesome-tray/commit/b72962fc774ab76c65812e7d9d02e5215bc254cd

应该修复了， 不同语言定义class和function的名称不一样， 只能慢慢穷举了， 都能修复。
