### ISSUE TITLE
How to set active line color?

### ISSUE THREAD

**Issue by orazdow** [manateelazycat/awesome-tray#117]
I have tried to set the line color with `(setq awesome-tray-mode-line-active-color "#7BDFCB")`

When emacs starts, the line is still red and I get these warnings:

```
Warning: setting attribute ‘:background’ of face ‘mode-line-buffer-id’: nil value is invalid, use ‘unspecified’ instead.
AppData/Roaming/.emacs.d/awesome-tray/awesome-tray.el: Warning: Pattern t is deprecated.  Use `_' instead [2 times]
Unable to load color "color" [2 times]
```
edit: those errors seem to be there anyway

What is the correct way I should be setting the color?

**Comment by manateelazycat** [comment]
Use color in  list-colors-display
