### ISSUE TITLE
color-rg 的提示栏会被 awesome-tray 覆盖

### ISSUE THREAD

**Issue by oLd-Y** [manateelazycat/awesome-tray#122]
# 问题
同时安装 color-rg 和 awesome-tray 时，color-rg 的提示栏会被遮挡，如下所示。（多显示器不知道为啥截不全，勿介意）

![image](https://github.com/manateelazycat/awesome-tray/assets/71266297/1d0321ba-bf7a-4272-a333-9eaf079ec16b)

经测试，是 awesome-tray 导致的这个问题。

# 最小复现
新建 `.emacs.d` 文件夹:
```shell
cd .emacs.d
git clone --depth 1 https://github.com/manateelazycat/awesome-tray
git clone --depth 1 https://github.com/manateelazycat/color-rg
```

新建 `init.el` 文件:
```elisp
(add-to-list 'load-path "~/.emacs.d/awesome-tray")
(add-to-list 'load-path "~/.emacs.d/color-rg")

(use-package awesome-tray
    :config
    (awesome-tray-mode))
(use-package color-rg)
```

打开 emacs 并使用 color-rg-search-input 进行搜索

---

此外，执行某些加载主题的代码时，例如：

```elisp
(use-package doom-themes
  :ensure t
  :config
  (doom-themes-org-config)

  (let ((theme (if (display-graphic-p)
                   'doom-one
                 'doom-Iosvkem)))
    (load-theme theme t)))
```
可以临时解决问题，但下次重启 emacs 之后还是会出现同样的问题。

**Comment by manateelazycat** [comment]
看你的截图， 是你装了什么插件定制了 header-line 导致 color-rg 被覆盖了， 不是 awesome-tray 的原因， 这两个插件我天天都在组合用的， 没有你说的问题。

**Comment by oLd-Y** [comment]
但问题是我用 emacs -Q 只装了这两个插件也会出现这个问题啊[捂脸]。

![image](https://github.com/manateelazycat/awesome-tray/assets/71266297/f863f593-a799-4fea-b930-98b84f6e3915)

这里的搜索结果也是没有提示栏的。

*scratch* 只有这些代码：

```elisp
(add-to-list 'load-path "~/awesome-tray")
(add-to-list 'load-path "~/color-rg")

(use-package awesome-tray
    :config
    (awesome-tray-mode))
(use-package color-rg)
```

虽然不影响使用，但还是想知道哪里出现了问题。猫哥能给点排错的思路吗，不能的话就只能将就着用了。

系统是 arch， 桌面是 kde + wayland

**Comment by manateelazycat** [comment]
我不太明白， 你画框的地方叫 header-line, header-line 在 color-rg 是被自定义的 https://github.com/manateelazycat/color-rg/blob/38d60658494ea3093ff3121458736a2eb6ab2b1b/color-rg.el#L662

所以在 color-rg 里面不会显示别的 header-line 插件， 我也觉得没有必要显示 header-line, 因为 color-rg 就是一个全局的临时搜索buffer
