### ISSUE TITLE
Line number display incorrect when use "M-<" or "M->"

### ISSUE THREAD

**Issue by zw963** [manateelazycat/awesome-tray#13]
## reproduce

### Press "M->"

i can see `(1:0 top)` no changed, this is not expected.

i expect to see "(70:0 bottom)"

### Press "Ctrl+p",  will move one line up, 

we see (69:0 99%), this is expected.

### solution

It seem like when press "Ctrl+>" or "Ctrl+<", some hook not happen which should update
line number.

Emacs 26.1 + newest commit fdda61e

Thank.

**Comment by manateelazycat** [comment]
Please update to newest version, has fixed.

Thanks for report. ;)

**Comment by zw963** [comment]
Yes, it worked, thank you very much!

**Comment by zw963** [comment]
hi, @manateelazycat , i consider above issue still exist in newest master. (9a9d721)

following is some explain:

1. current on line 1 => (1:0 Top), it worked.
2. press Ctrl + > , => (96:0 Bottom), it worked.
3.  press Ctrl + <, => (64:0 Bottom),  i think this 64 is the current screen the first line.
4.  after one second, restore to (1:0 Top)

Thank you.
