### ISSUE TITLE
Performance issue with awesome-tray-module-location-info

### ISSUE THREAD

**Issue by vuquangtam** [manateelazycat/awesome-tray#14]
When editing large file (org file with 20000 lines), the location module is very slow. I inspected the code and found out it cause by `(line-number-at-pos (point-max))` and `(line-number-at-pos)`. So i try to replace those function with better solution and it get much more faster.
- Original
```
(defun awesome-tray-module-location-info ()
  (let* ((bottom-line (line-number-at-pos (point-max)))
         (location-percent
          (cond ((equal (line-number-at-pos) 1)
                 "top")
                ((equal (line-number-at-pos) bottom-line)
                 "bottom")
                (t
                 (format "%.f%%" (* (/ (float (line-number-at-pos)) bottom-line) 100))))
          ))
    (format "(%s:%s %s)"
            (line-number-at-pos)
            (current-column)
            location-percent
            )))
```

- I replace `(line-number-at-pos (point-max))` with [`total-lines-mode`](https://github.com/hinrik/total-lines) and `(line-number-at-pos)` with `(string-to-number (format-mode-line "%l"))`
```
(defun awesome-tray-module-location-info ()
          (let* ((bottom-line (if (numberp total-lines) total-lines (line-number-at-pos (point-max))))
                 (current-line (string-to-number (format-mode-line "%l")))
                 (location-percent
                  (cond ((equal current-line 1)
                         "top")
                        ((equal current-line bottom-line)
                         "bottom")
                        (t
                         (format "%.f%%" (* (/ (float current-line) bottom-line) 100))))
                  ))
            (format "(%s:%s %s)"
                    current-line
                    (current-column)
                    location-percent
                    )))
```

**Comment by manateelazycat** [comment]
I commit new patch https://github.com/manateelazycat/awesome-tray/commit/7ac7fafd4d4b4396b4c69af73b02e8b538a94cc4 to fixed this problem.

I have test 40000 lines in MacBook Pro, works fine.

total-lines package is hacking way, i don't think it's right way to fix problem.

Thanks for report this issue! ;)

**Comment by vuquangtam** [comment]
You're right total-lines is hacking solution, it has side-effect that affect other packages. I retry but it's still slow . This is my [file](https://gist.github.com/vuquangtam/f669f4cb00e05b6f74a92953f10c0d2a). The root cause is (line-number-at-pos (point-max)), it took about 3s to finish.
After digging on emacs documentation, i found that emacs built-in modeline has already have a solution for this module, and also have better solution, this [documetation](https://www.gnu.org/software/emacs/manual/html_node/elisp/_0025_002dConstructs.html#g_t_0025_002dConstructs). My fix for this

```
(defun awesome-tray-module-location-info ()
          (let* ((current-line (format-mode-line "%l"))
                 (current-column (format-mode-line "%c"))
                 (location-percent (format-mode-line "%p")))
            (format "(%s:%s %s)"
                    current-line
                    current-column
                    location-percent
                    )))
```

**Comment by manateelazycat** [comment]
> You're right total-lines is hacking solution, it has side-effect that affect other packages.
> I retried [7ac7faf](https://github.com/manateelazycat/awesome-tray/commit/7ac7fafd4d4b4396b4c69af73b02e8b538a94cc4) but it's still slow . This is my [file](https://gist.github.com/vuquangtam/f669f4cb00e05b6f74a92953f10c0d2a). The root cause is (line-number-at-pos (point-max)), it took about 3s to finish.
> After digging on emacs documentation, i found that emacs built-in modeline has already have a solution for this module, and also have better performance, this [documetation](https://www.gnu.org/software/emacs/manual/html_node/elisp/_0025_002dConstructs.html#g_t_0025_002dConstructs). My fix for this
> 
> ```
> (defun awesome-tray-module-location-info ()
>           (let* ((current-line (format-mode-line "%l"))
>                  (current-column (format-mode-line "%c"))
>                  (location-percent (format-mode-line "%p")))
>             (format "(%s:%s %s)"
>                     current-line
>                     current-column
>                     location-percent
>                     )))
> ```

Done https://github.com/manateelazycat/awesome-tray/commit/f2d537c69f2c46d29846d3b461a8ca1de67760bb

Thanks for tips. ;)

**Comment by QiangF** [comment]
I have a file that has 1141879 lines, display-line-numbers-mode shows the line correctly, but 

    (format-mode-line "%l")

return ??
