### ISSUE TITLE
启动后 awsome-tab图标缩小

### ISSUE THREAD

**Issue by signorinotang** [manateelazycat/awesome-tray#15]
https://emacs-china.org/uploads/default/original/2X/b/be040bc03ecb5498524e54375619035c83448230.png
https://emacs-china.org/uploads/default/original/2X/7/7956809927a5baa60624ccf224230ef608b0b5f8.png

emacs -Q后的最小配置 插件都删了 最后执行 awsome-tray-mode 1 tab图标就会瞬间变小 执行前后https://emacs-china.org/uploads/default/original/2X/3/314d05c6a9a6b58b63ed4e716c8f5272b68b1ca0.png
https://emacs-china.org/uploads/default/original/2X/7/7fcc5897a8bf77b51c46f84dca5fa967aeb64d15.png

**Comment by signorinotang** [comment]
不能编辑了。。图片变成链接了 抱歉！~

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/awesome-tab/commit/51728429819601048929b9415421db4bbb157007

Thanks for report!
