### ISSUE TITLE
Do not message "Enable awesome tray"?

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-tray#20]
`awesome-tray-enable` messages "Enable awesome tray". I put it in my own load theme hook to have correct colors/mode line heights when changing theme, but it's annoying that everytime it messages "Enable awesome tray". I tried this:

``` emacs-lisp
(define-advice awesome-tray-enable (:around (fn) fix)
  "Suppress messaging."
  (cl-letf (((symbol-function 'message) #'ignore))
    (funcall fn)))
```

It works, but somehow it breaks the function `message`: when calling `message`, the string show for an instant, but then `nil` appears in the echo area. This should have something to do with `awesome-tray`'s advices.

Could we:

- Let `awesome-tray-enable` do not message anything? We know it's loaded since the tray is there.
- Or have a `awesome-tray-refresh` function for user to put in his/her own hooks?
- Or find a way to make the above advice work without breaking `message`?

**Comment by manateelazycat** [comment]
Done https://github.com/manateelazycat/awesome-tray/commit/0fde8a2bc7999564565670605339d1bb867e2bcc
