### ISSUE TITLE
How to darken faces for light themes?

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-tray#21]
如题，我打算给 awesome-tray 加一个在亮色背景下自动把文字 face 变暗的功能。我想到下面两种做法：

最简单的实现像是：

```
(defface awesome-tray-module-awesome-tab-face
  '((((background light))
     :foreground "#731E38" :bold t)
    (t
     :foreground "#E73C70" :bold t))
  "Awesome tab face."
  :group 'awesome-tray)
```

我可以用一个 `darken` 函数来把一个颜色变暗，但遗憾的是上述表达式中并不能用函数的返回值作为颜色，所以需要手动一个一个加上去。此外若用户自定义 face，也需要像这样手动来搞，体验不太好。

另一种办法是我们定义一堆空 face，再搞一堆 defcustom 指定各 module 在暗色主题下的前景色（或者处于「中间」的前景色，让用户指定纯度比较高的颜色，在亮暗主题下分别加暗或加亮，这可以讨论）。在 `awesome-tray-enable` 时根据背景的亮暗再设定 face，类似 `awesome-tab` 那样。但是这样阵仗有点大。

你怎么看？是否有更好一些的做法？

**Comment by manateelazycat** [comment]
最简单两个方法

1. 不同模块就使用变量，函数，常量等颜色
2. 不管他，用户自定义

我个人的感觉还是不管他，awesome-tray和awesome-tab不一样，tab定制颜色有点麻烦，而且跟随主题比较好看

tray就是自定义，花花绿绿才好看

我建议不要管主题方面细节，保持代码简单，用户可以自定义就很好了。

**Comment by AmaiKinono** [comment]
用 font lock 属性的话，一个是模块多了以后选择太少了，再一个是它们自身设计就有醒目度的区别，用在这感觉不太合适。我想我还是做我说的第一种方案，满足你说的保持代码简单，可以让用户自定义，但是开箱体验可以好一些。

**Comment by manateelazycat** [comment]
就是可以自定义就好了，其实Emacs用户都喜欢自定义，适应主题反而不好
