### ISSUE TITLE
Can't exit Emacs when using wrong modules.

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-tray#22]
我没有用 circe 这个包。今天测试一些 face 的时候启用了 “circe” 模块，然后 awesome-tray 报错：

```
Wrong type argument: listp, "Sorry, something error in awesome tray."
```

且 Emacs 无法退出，退出时 modeline 会闪，并且重复报这个错。我估计可能是因为 awesome-tray 给一些 minibuffer 相关的函数加了 advice，而退出时 Emacs 还想要 message 什么信息，就一直卡在这个错误里了。

*Update:* 在开发 evil 模块的时候我发现如果模块的 `info` 函数出错，awesome-tray 就会报这个错。或许应当使得 `info` 函数出错时自动用 `""` 代替其返回值，这样 `info` 函数就不需要太细致地处理错误。

**Comment by manateelazycat** [comment]
我觉得不要绕圈子，如果awesome-tray报这个错误，正确的方式应该是修复它，而不是用 “” 忽略它。

**Comment by AmaiKinono** [comment]
这个我觉得不是这样。首先在开发一个模块的过程中，如果看到 awesome-tray 没有显示它，就已经说明 info 函数写得有问题，那去查它的错就是了。如果一个模块的问题会导致 awesome-tray 整个挂掉，甚至不能退出 Emacs，那开发体验也太糟糕了。其次如果不做这个机制，我们在 info 函数里用 `with-demote-error`，用条件判断，把这个函数写得滴水不漏，实际上做的事情也还是获取不到信息时返回 `""` 而已，那不如用统一机制给它兜底，这样还能少一些 boilerplate 代码。实现上也并不难，我可以在做 https://github.com/manateelazycat/awesome-tray/issues/25 的同时把这个做了。

**Comment by manateelazycat** [comment]
你先先补丁吧，我乐见其成，哈哈哈哈
