### ISSUE TITLE
Consider a declarative scheme to add modules?

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-tray#25]
Currently a module can't be added without touching `awesome-tray`'s codebase. Sometimes a user may want to have some private modules to satisfy his/her demand. I suggest we refactor `awesome-tray-get-module-info` to read the logic from an alist like:

``` emacs-lisp
(("git" . '(awesome-tray-module-git-info awesome-tray-module-git-face)
 (...))
```

so user can push his module name, info function and face into this list. I can do this if you consider it reasonable.

**Comment by manateelazycat** [comment]
可以改，你加吧 ;)
