### ISSUE TITLE
Truncate awesome-tab information?

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-tray#26]
Awesome-tab often give us a long project directory like:

```
Project: /home/kino/.emacs.d/straight/repos/awesome-tray/
```

It would be better to simply show

```
Project: awesome-tray
```

or

```
Project: .../s/r/awesome-tray/
```

In fact, I think it's better for "parent-dir" module to show `.../s/r/awesome-tray`, and "awesome-tab" module can show `Project: awesome-tray`.

**Comment by AmaiKinono** [comment]
等一下，这个 issue 还没有完全解决，请再考虑一下。我说的是 `awesome-tab` 模块显示的路径过长的问题，需要关注路径信息的话可以用 `parent-dir` 或 `file-path` 模块，所以应当尽量截短 `awesome-tab` 的信息。

**Comment by manateelazycat** [comment]
比如有两个目录：

1. /home/andy/awesome-tab
2. /home/andy/lazycat-emacs/extensions/awesome-tab

如果要做缩短，可以考虑 .../andy/awesome-tab/ 和 .../extensions/awesome-tab ，如果只是一味的做 parent-dir 缩短，其实有时候脑袋还要想一下 parent-dir 是啥，我觉得就显示 current-dir 和 parent-dir 就足够分辨不同位置的相同目录，如果 parent-dir 都是一样的，这种情况我觉得不用考虑。

尽量让目录的信息简单直接，用户瞟一眼就能够看明白，不要让用户去研究 .../s/r/awesome-tab 路径中 s 和  r 到底是啥？

**Comment by AmaiKinono** [comment]
你说的路径的问题，可以改 file-path 模块或者再写新的来解决。但是我想的是，awesome-tab 模块主要是看 tab 的分组信息，不是路径，不然为什么我打开一个 el 文件它显示一个 Elisp 分组而不是路径？所以当 awesome-tab 模块给出 "Project: ..." 形式的信息时，只需要留下最后一个目录名作为工程的名字。想关心路径的用户自然会用别的模块的。

**Comment by manateelazycat** [comment]
主要我自己的 lazycat-emacs 下的 submodule 和我 ~ 目录下的开发目录都是相同的项目名字，如果只显示最后一个，我反而认不得了。

我们再想想吧，不急于下结论。

**Comment by manateelazycat** [comment]
不管是 file-path 路径还是 awesome-tab 路径，如果要缩短，可以显示量级目录，再上级可以 ... ， 但是如果只显示最后一个，短是短，但是不实用。

**Comment by AmaiKinono** [comment]
> 主要我自己的 lazycat-emacs 下的 submodule 和我 ~ 目录下的开发目录都是相同的项目名字

我理解了。这样确实用一级目录作为工程名字就不妥了。

> 不管是 file-path 路径还是 awesome-tab 路径，如果要缩短，可以显示两级目录，再上级可以 ...

现在 file-path 模块可以定制，想要怎么显示就怎么显示，但实际上就和 awesome-tab 模块的功能有些重合了。我发现我在一个工程里的时候我会想要看 file-path，在写 elisp/org 之类的时候不用说我也知道它在那些特殊 group 里，所以我已经把 awesome-tab 模块排除了。或许我们应该想的是，如果一个人不开 file-path/parent-dir，但是开着 awessome-tab，那他是想看什么呢？

**Comment by manateelazycat** [comment]
其实 file-path 更多像一个二级路径，主要作用是区分不同位置的相同目录，目标是区分开发版本和正式版本

awesome-tab 更多是一种 project + 特殊分组，主要是用于快速区分和切换到不同的 project 分组

我觉得主要是能够区分，使用的情况下尽量短就可以了，Emacs本身就是千人千面，不用追求最简洁和最优化，有就挺好，模块之间功能稍微重复点没关系

**Comment by manateelazycat** [comment]
这个issue先关了？

**Comment by AmaiKinono** [comment]
OK, 等你啥时候有灵感再搞吧 ;)
