### ISSUE TITLE
awesome-tray-disable incorrectly recovers modeline height 

### ISSUE THREAD

**Issue by zevlg** [manateelazycat/awesome-tray#34]
Disabling awesome-tray makes modeline height to be 0.1pt.  Documentation states that float number must be used as value for `:height` to apply it as scaling factor.  Anyway, even 1.0 as `:height` value is not good, because user might have custom `:height` for modeline, that is exactly my situation

Thanks

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/awesome-tray/commit/637d25bb1637cfe3a6264e3718e8e82a31d5702e
