### ISSUE TITLE
Awesome tray and hotkeys

### ISSUE THREAD

**Issue by n1rdeks** [manateelazycat/awesome-tray#39]
If i use hotkeys (C-a C-e or M-b M-f of cursor move C-f C-b), "awesome-tray" all refresh. 

Another situation for blinking - "beginning buffer" and "end of buffer". Just press 'up' in begin file, all
data in tray lost (name, mode etc).

**Comment by KiteAB** [comment]
this issue still exists @manateelazycat

**Comment by manateelazycat** [comment]
I haven't.idea now

**Comment by n1rdeks** [comment]
well... Maybe later.
