### ISSUE TITLE
Windows下使用导致卡顿

### ISSUE THREAD

**Issue by cireu** [manateelazycat/awesome-tray#4]
* 问题描述
你好! 我尝试了您的awesome-tray后, 感觉十分好用. 不过我发现如果打开含有git信息的文档, Emacs就会变得十分卡顿甚至失去相应.

为了防止其他包的干扰结果, 使用`emacs -Q`最小化启动, 单独载入awesome-tray并打开profiler.
结果如图所示.
![tim 20181027182138](https://user-images.githubusercontent.com/18224684/47602710-300b1080-da15-11e8-9617-a23a98cb3599.png)

似乎CPU大部分时间忙于处理git信息的更新, 而在windows下启动进程比较昂贵, 可能这就是导致卡顿的原因.

* 我的一点点建议
Git分支信息不同于行号和列号当前时间这种实时更新的信息, 是相对比较固定的. 可以将其缓存下来, 避免了反复调用Git开销严重, 进而导致性能问题

**Comment by manateelazycat** [comment]
缓存下来很有可能无法工作, 因为对于Emacs什么状态(目录, buffer, window等)都没有改变, 当前git仓库的分支也有可能已经被任何执行git命令的操作所改变.

我还没有想到非常好的方法去改建这一点, 建议你可以先把  git 模块禁用了, 等我想到更好的方法去改进这个问题.

当然, 如果你又更好的方法, 欢迎提供想法, 谢谢.

**Comment by cireu** [comment]
好的，谢谢猫哥。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/awesome-tray/commit/6630ac2c0073bb763fcd7eb2f4603019fa12f5e2 把这个选项设置大一点吧, git分支信息更新会有延迟.
