### ISSUE TITLE
Include org-pomodoro clock

### ISSUE THREAD

**Issue by rvf0068** [manateelazycat/awesome-tray#40]
The org-pomodoro clock (https://github.com/marcinkoziej/org-pomodoro) is not displayed. How would one show this (or any org-mode clock)?

**Comment by manateelazycat** [comment]
Any PR we welcome ;)

**Comment by KiteAB** [comment]
> The org-pomodoro clock (https://github.com/marcinkoziej/org-pomodoro) is not displayed. How would one show this (or any org-mode clock)?

can u try find a variable or function to export pomodoro clock and write a module for awesome tray?

**Comment by xinyifly** [comment]
```
org-pomodoro-mode-line is a variable defined in ‘org-pomodoro.el’.
Its value is
("["
 #("Pomodoro~24:55" 0 14
   (face org-pomodoro-mode-line))
 "] ")
```

```
org-mode-line-string is a variable defined in ‘org-clock.el’.
Its value is shown below.

Value:
#(" [0:00] (Org Demo Task)" 0 23
  (local-map
   (keymap
    (mode-line keymap
               (mouse-1 . org-clock-menu)
               (mouse-2 . org-clock-goto)))
   mouse-face mode-line-highlight face org-mode-line-clock help-echo "Org mode clock is running.
mouse-1 shows a menu
mouse-2 will jump to task"))
```

These two variables is somehow been showed in `mode-line-misc-info` .

I think verbosely getting `mode-line-misc-info` to be showed in awesome-tray is a method to achieve that.

**Comment by manateelazycat** [comment]
Have add
