### ISSUE TITLE
occur with "minibuffer-inactive ... ..."

### ISSUE THREAD

**Issue by fu123456** [manateelazycat/awesome-tray#45]
I found that I use vr/replace, and my emacs output some undesirable information as follows:
![94637921-4f023380-030b-11eb-9e0f-27181d29cafc](https://user-images.githubusercontent.com/22411577/95476965-27087500-0988-11eb-9f51-07322c5e88df.png)
So, I want to know how to prohibit this message which is often nosiy. Thanks.

**Comment by manateelazycat** [comment]
I have test it.

I think we can't fix this in awesome-tray, visual-regexp use magic code that I can't write workaround patch to fix this issue, sorry.
