### ISSUE TITLE
awesome tray showing on left side

### ISSUE THREAD

**Issue by HumHongeKamyaab** [manateelazycat/awesome-tray#46]
I am using following instructions to install awesome tray using `use-package` and `straight`, but awesome tray is showing on left side of the minibuffer. How can I resolve this issue.
```
(use-package awesome-tray
  :straight (:host github
             :repo "manateelazycat/awesome-tray"
             :branch "master")
  :config
  (awesome-tray-mode 1)
  (setq awesome-tray-active-modules '("location" "buffer-name" "git" "mode-name" "evil"))
  )
```

**Comment by manateelazycat** [comment]
Please use emacs -Q test it.

**Comment by manateelazycat** [comment]
I am not use use-package or straight.

Please use "emacs -Q" test, and avoid compile to elc.
