### ISSUE TITLE
modeline still exists when change or load theme

### ISSUE THREAD

**Issue by 404cn** [manateelazycat/awesome-tray#52]
OS: Mac OS Big Sur 11.0.1

GNU Emacs 27.1

<img width="1082" alt="CleanShot 2020-12-02 at 23 46 12@2x" src="https://user-images.githubusercontent.com/24653356/100895550-a7ff6b00-34f8-11eb-8c0b-d44361b6c75f.png">

**Comment by manateelazycat** [comment]
you need check lazycat theme

many theme not support hide mode line
