### ISSUE TITLE
Awesome-tray seems to be interfering with `emacsclient`

### ISSUE THREAD

**Issue by jvillasante** [manateelazycat/awesome-tray#56]
I'm using `awesome-tray` with `doom-emacs` and it works *awesome* and I love it on GUI mode. However, when starting `emacs` with daemon and using `emacsclient` to connect to it it looks like `awesome-tray` interferes somehow. The mini-bufer just does not stays up while I try to complete a file path on it, it keeps hiding itself as seen in the gift below. If I disable `awesome-tray` or instead of using `emacsclient -t -a ''` I use `emacs -nw` everything works as expected. 

![2021-10-31 07 40 00](https://user-images.githubusercontent.com/1139125/139581547-08831933-39f0-4369-9e75-61ea7303cbb6.gif)

**Comment by manateelazycat** [comment]
Can you test it with "emacs -Q", and don't use any doom emacs config for compare?

**Comment by jvillasante** [comment]
Wouldn't `emacs -Q` disable `awesome-tray` also?
And, it works perfectly when running `emacs -nw` even with doom configs.
I'll try to run other tests if I can.

**Comment by jvillasante** [comment]
So, I had some time and did some debugging. I have *zero* elisp skills, only take this as an indication for your own work.

```
(defun awesome-tray-flush-info ()
  (let* ((tray-info (awesome-tray-build-info)))
    (with-current-buffer " *Minibuf-0*"
      (erase-buffer)
      (insert (concat (make-string (max 0 (- (awesome-tray-get-frame-width) (string-width tray-info) awesome-tray-info-padding-right)) ?\ ) tray-info)))))
```

In the function `awesome-tray-flush-info()`, if I replace the call to `awesome-tray-get-frame-width()` with just `frame-width()` it starts working in terminal too with `emacsclient`. I don't know why this is the case but probably you know better and this shed some light into the issue.

Also, for context, I'm running `emacsclient` inside `tmux` on `alacritty`. I thought it could be my config somehow but the issue also happens when running `emacsclient` on plain `iterm`.

**Comment by manateelazycat** [comment]
@jvillasante Try newest version ? I have push new patch: https://github.com/manateelazycat/awesome-tray/commit/a071f2928da1fd4b545ef642511a10100d39e52a

**Comment by jvillasante** [comment]
Yes, that's exactly the fix I came up with and it now works as expected.
This issue can be closed. Thanks!

**Comment by marioba** [comment]
I have the same issue with the latest version.
Launching a "normal" Emacs instance everything works fine but if I launch it using emacsclient I have the same issue reported here.

With @jvillasante's patch (`frame-width()` instead of `awesome-tray-get-frame-width()`) it works correctly.
