### ISSUE TITLE
Conflict with headerline of lsp-mode

### ISSUE THREAD

**Issue by coldnight** [manateelazycat/awesome-tray#57]
Hey, when awesome-tray was enabled, the headerline of lsp-mode was messed. Here is the screenshot:
![image](https://user-images.githubusercontent.com/2527265/147188161-8ad543e6-7206-4a25-94c7-0c38d57fc84c.png)

**Comment by coldnight** [comment]
I think the reason is the  `height` of mode-line face was set to 0.1 by [here](https://github.com/manateelazycat/awesome-tray/blob/35b4c301d768cba199b73bac8270f2e4415673a1/awesome-tray.el#L519-L529). Manually set to 1 fixed this, but the mode-line is also affected:

```elisp
  (set-face-attribute 'mode-line nil
                      :foreground awesome-tray-mode-line-active-color
                      :background awesome-tray-mode-line-active-color
                      :height 1
                      :box nil)
```

**Comment by manateelazycat** [comment]
awesome-tray design for 0.1 height, yes,it's conflict, no way to fix conflict

**Comment by coldnight** [comment]
After dig a little deeper, I found all the face-attributes of header-line is `unspecified`. 

```elisp
(face-all-attributes 'header-line)
```

That may make header-line affected to face-attributes of mode-line. So I think it will be fixed if we set header-line face-attributes alone, and it works:
```elisp
  ;; Copy mode-line's face-attributes to the header-line,
  ;; to avoid the face-attributes is changed by awesome-tray that effects to header-line too.
  (set-face-attribute 'header-line nil
                      :foreground (face-attribute 'mode-line :foreground)
                      :background (face-attribute 'mode-line :background)
                      ;; :height of mode-line is also unspecified,
                      ;; here
                      :height 150
                      :box (face-attribute 'mode-line :box))
```
