### ISSUE TITLE
Awesome-Tray hides vertico completions when using daemon.

### ISSUE THREAD

**Issue by sdquinlan** [manateelazycat/awesome-tray#58]
Awesome-tray works fine with vertico when run via emacs.exe, however when using emacsclientw.exe to connect to a daemon awesome tray inhibits the display of vertico completions. The candidates will appear momentarily, and then be suppressed.

Emacs also throws this message(s) when connecting to the daemon:

Invalid face reference: awesome-tray-module-file-path-face
Invalid face reference: awesome-tray-module-mode-name-face
Invalid face reference: awesome-tray-module-date-face
Invalid face reference: awesome-tray-module-input-method-face

These messages do not appear when running without the daemon.

This occurs if running awesome-tray via the init.el or via M-x.

**Comment by jvillasante** [comment]
This also happens to me, on Fedora Linux when running emacs as a server and then connecting with a client:
```
emacs --daemon # run the daemon
emacsclient -c -n -a '' # connect to the daemon
```

on the `emacsclient` instance, the minibuffer will appear, then disappear only to appear again...

**Comment by manateelazycat** [comment]
Please don't use awesome-tray in daemon mode.
