### ISSUE TITLE
输入法那里 minibuffer 还是一闪一闪的

### ISSUE THREAD

**Issue by nesteiner** [manateelazycat/awesome-tray#59]
https://user-images.githubusercontent.com/46296608/156491311-1e861c6c-ca28-4383-8a6a-49177963b906.mp4

**Comment by nesteiner** [comment]
我用的新版本

**Comment by manateelazycat** [comment]
你输入法用posframe模式呀，你占用minibuffer，肯定闪呀，论坛已经有人回答你了啊。
