### ISSUE TITLE
Is there a alternative way to pad right by overlay?

### ISSUE THREAD

**Issue by coldnight** [manateelazycat/awesome-tray#60]
Hey, I noticed the option `awesome-tray-info-padding-right` had been removed by commit 00047f4a8a466f072f2047c50258b5b8fbc30381.

Without that option the last one character of awesome-tray in my Emacs always goes to the new line, check out the screenshot:
![image](https://user-images.githubusercontent.com/2527265/162870522-c7891351-9968-49a6-9c38-e4b306d45b26.png)

And instead of, we are now using overlay, I want to know how to make the same purpose with overlay.

**Comment by manateelazycat** [comment]
@coldnight Fixed, thanks for report. ;)
