### ISSUE TITLE
Option for customize module.

### ISSUE THREAD

**Issue by vuquangtam** [manateelazycat/awesome-tray#7]
Hi, thank for making awesome package. Can you add way to add custom module to traybar (like symon-mode). Thank a lot.

**Comment by manateelazycat** [comment]
## Customize
You can controll modules through option ```awesome-tray-active-modules```
You can find all modules name through variable ```awesome-tray-all-modules```

Similar patch you can look https://github.com/manateelazycat/awesome-tray/pull/8
