### ISSUE TITLE
Can we show filename in the tray ?

### ISSUE THREAD

**Issue by avatar-lavventura** [manateelazycat/awesome-tray#82]
Can we also show the filename in the tray instead of having it on top of the buffer?

**Comment by manateelazycat** [comment]
can you screenshot to explan your mean?

**Comment by avatar-lavventura** [comment]
I don't know how can I explain simplier. In your README.md 

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/18537398/179347461-364d7b9f-6d52-4486-9035-23a90590a91e.png">

The buffer name located at the top. Instead can it be located at the bottom of the buffer, next to them: 

<img width="735" alt="image" src="https://user-images.githubusercontent.com/18537398/179347527-7636e19d-a6c7-4991-99bf-6a7863c4e3df.png">

**Comment by manateelazycat** [comment]
its awesome-tab or sort-tab, not awesome-tray feature

**Comment by avatar-lavventura** [comment]
You should put the example image into README.md without `awesome-tab` or `sort-tab`.
