### ISSUE TITLE
tooltip message does not show in minibuffer

### ISSUE THREAD

**Issue by LuoPX-15510486969** [manateelazycat/awesome-tray#9]
thoes messages need you to make choice should display in minibuffer, or you dont konw what happed .for example ,emacs is waiting for your type.
![onekey](https://user-images.githubusercontent.com/13256245/50543396-9c231400-0c12-11e9-89af-38476a1a73e8.gif)

**Comment by manateelazycat** [comment]
我已经用代码
```
 (y-or-n-p "hello: ")
```

代码测试过了, 没有问题.

你的现象看着更像组合键只按了前半部分
