### ISSUE TITLE
Default tray wraps to a second line

### ISSUE THREAD

**Issue by trev-dev** [manateelazycat/awesome-tray#90]
It doesn't look right...is it just me?

![awesome](https://user-images.githubusercontent.com/28788713/190548968-0e137394-8cb0-4691-a562-47d5401ff8f3.png)

**Comment by LucasTavaresA** [comment]
this was happening before the second line option has been added, im not sure why
set `awesome-tray-info-padding-right` to more than zero that fixes it most of the time

**Comment by trev-dev** [comment]
A setting of 1 did the trick! Thank you

**Comment by trev-dev** [comment]
Correction - 2 did the trick! It was still wrapping on the minibuffer prompt.

This is a really cool project btw. I enjoy that the "mode-line" is uniform no matter how many splits I have got.

**Comment by manateelazycat** [comment]
> It doesn't look right...is it just me?
> 
> ![awesome](https://user-images.githubusercontent.com/28788713/190548968-0e137394-8cb0-4691-a562-47d5401ff8f3.png)

It's because your customize some font that awesome-tray can't calc width correctly, you need set `awesome-tray-info-padding-right` to fix this issue that cause by customzie font.

**Comment by trev-dev** [comment]
> > It doesn't look right...is it just me?
> > ![awesome](https://user-images.githubusercontent.com/28788713/190548968-0e137394-8cb0-4691-a562-47d5401ff8f3.png)
> 
> It's because your customize some font that awesome-tray can't calc width correctly, you need set `awesome-tray-info-padding-right` to fix this issue that cause by customzie font.

It's a monospace font called "Hack". What kind off font works best with awesome-tray?
