### ISSUE TITLE
mode-line is very weird when using org clock

### ISSUE THREAD

**Issue by Ryan19929** [manateelazycat/awesome-tray#93]
before
<img width="1510" alt="图片" src="https://user-images.githubusercontent.com/43268112/195533172-f73f454b-48df-48c2-a6e9-b45750839df0.png">

after
<img width="1502" alt="图片" src="https://user-images.githubusercontent.com/43268112/195523156-fd4f9ce3-2786-44d7-a6a7-0c1ccbe0cef4.png">

When I use org-clock, the disabled mode-line will be weird. (org-clock-clocked-display in mode-line default)

Awesome-tray-hide-mode-line is not-nil, the thin mode-line become not thin.

I know  disable the org-clock-clocked-display will become thin mode-line . But is this normal?

**Comment by LucasTavaresA** [comment]
when you disable awesome-tray-hide-mode-line and set mode-line-format to nil any packages that mess with the mode-line can re-enable the mode-line, packages like anzu have an option to disable that without disabling the functionality and you can use an advice to deal with the info instead

**Comment by Ryan19929** [comment]
> 用中文吧， 我没看懂你说的英文是啥意思？

不好意思，英语不太好。就是在使用hide-mode-line的时候，org-clock会默认在mode-line上添加一个clock，会让之前隐藏变成很细的mode-line变回原来的高度，并且高亮，效果就是之前的after，看上去非常奇怪。

**Comment by Ryan19929** [comment]
> when you set `awesome-tray-hide-mode-line` and `mode-line-format` to nil any packages that mess with the mode-line can re-enable the mode-line, packages like anzu have an option to disable that without disabling the functionality and you can use an advice to deal with the info instead
> if both variables are nil this is unexpected

Thank you! I disable the function and use the org-clock module.
