### ISSUE TITLE
Minibuffer里cursor表现异常

### ISSUE THREAD

**Issue by jinnovation** [manateelazycat/awesome-tray#94]
一旦想在minibuffer输入，比如使用`M-x`时，cursor会使minibuffer中间变全白。

<img width="1717" alt="image" src="https://user-images.githubusercontent.com/1932579/209853927-160e102d-d3e2-441b-9521-f955640601f8.png">

不知是否和我其他安装的包有冲突。

**Comment by LucasTavaresA** [comment]
this is not caused by other packages, long time since i tried it but i think this happens in emacs-pgtk, are you on emacs-pgtk?

**Comment by manateelazycat** [comment]
是有这个问题， 暂时没有想到好的解决方案。

**Comment by jinnovation** [comment]
好的，那么暂时留拿这issue当个记录吧。👍

**Comment by manateelazycat** [comment]
晚上想到一个点子， 更新试一下吧， 应该好了。

**Comment by jinnovation** [comment]
"Solve the problem by removing the need to solve it" 😆 

谢了，这样好多了。
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/1932579/209974054-b4ab3e6c-5cc5-461e-b459-b1498e3ab604.png">
